### ISSUE TITLE
Launch to Production Checklist

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/topichub#358]
Users
- [x] Gather feedback from testers to ensure they are happy
- [x] Confirm date to which they want Items to flow from the hub to the production DSpace collection
- [x] Configure channel to production DSpace collection (they should probably be asked to do this as it would be better to use their credentials and not our own for that production Channel).

Ops
- [x] Alert ops that this is happening so at minimum they know to direct fixlib tickets to us
- [x] See if ops has that Logstash server for us. If not, we'll be fine with the free hosted loggers for now.

App
- [x] ElasticSearch: the free plan we are on is soft capped to 10k documents. We're at 10.7k. We need to move to another plan as I'm sure they'll eventually cut us off. Bonsai gets real expensive real fast so we should look elsewhere. Possibly requesting Ops to create something for us somewhere (cloud or otherwise).
- [x] push latest code
